### ISSUE TITLE
want the paper 

### ISSUE THREAD

**Issue by ZihaoZheng98** [SarG93/uncond-sggen#1]
Hi, congratulations on the acceptance of the paper, the title of the paper really attract me, I wonder if it is convenient to get a pdf of this paper?  My email address is zhengxiaoxiehit@gmail.com. Thanks!

**Comment by SarG93** [comment]
Hello, thank you for the wishes. We added the paper on arxiv recently https://arxiv.org/pdf/2108.05884.pdf
